name = "Kotrarot"
author = "OffsetMonkey538"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "589672ec17d96360bfaca8ebb32cb5910eb899791eb46c422c02dbc537bab567"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
