name = "Kotrarot"
author = "OffsetMonkey538"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b72226b2017c763d87f3d40a9971d3de01469a1f1171c69d25d19b83b0716d35"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
