name = "Kotrarot"
author = "OffsetMonkey538"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f3168a2e823561b4bacf4224571386706cef0c562e0f55ec560372a8f34c6b3"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
